version: "3.8"

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: "mongodb://root:root@db:27017"

  db:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo:/data/db

volumes:
  mongo: