name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: clone-project
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Install flyctl
        #if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          curl -sL https://fly.io/install.sh | sudo sh
          fly version

      - name: Deploy app with fly.staging.toml
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: flyctl deploy --config fly.staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy app with fly.prod.toml
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: flyctl deploy --config fly.prod.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
