  name: build

  on:
    push:
    pull_request:

  jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: clone-project
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Unit Tests run
        run: mvn -B test --file pom.xml
