name: Fly Deploy Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit, branch or tag to deploy'
        required: false

jobs:
  deploy:
    name: Deploy app to staging
    runs-on: ubuntu-latest
    steps:
      - name: clone-project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MONGO_CLUSTER_LINK_STAGING: mongodb+srv://admin:admin@staging.wbvhwjt.mongodb.net/?retryWrites=true&w=majority
          MONGO_NAME_STAGING: Staging

      - name: Deploy if build succeeds
        uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only -c fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}